"""Initial schema

Revision ID: ca475caee2cf
Revises: 
Create Date: 2026-03-26 10:36:18.257905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca475caee2cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('scan_run_id', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_level'), 'audit_logs', ['level'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_table('bulk_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('deal_date', sa.Date(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('deal_type', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'deal_date', 'client_name', 'deal_type', name='uq_bulk_deal')
    )
    op.create_index('idx_bulk_deals_date', 'bulk_deals', [sa.literal_column('deal_date DESC')], unique=False)
    op.create_index(op.f('ix_bulk_deals_id'), 'bulk_deals', ['id'], unique=False)
    op.create_index(op.f('ix_bulk_deals_symbol'), 'bulk_deals', ['symbol'], unique=False)
    op.create_table('market_data_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mdc_symbol_type', 'market_data_cache', ['symbol', 'data_type'], unique=False)
    op.create_index(op.f('ix_market_data_cache_expires_at'), 'market_data_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_market_data_cache_id'), 'market_data_cache', ['id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stocks_scanned', sa.Integer(), nullable=True),
    sa.Column('signals_found', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_secs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('idx_scan_runs_started_at', 'scan_runs', [sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('ix_scan_runs_id'), 'scan_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_runs_started_at'), 'scan_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_scan_runs_status'), 'scan_runs', ['status'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('market_cap_cr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('nse_code', sa.String(length=20), nullable=True),
    sa.Column('bse_code', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_sector'), 'stocks', ['sector'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_item')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume_today', sa.BigInteger(), nullable=True),
    sa.Column('volume_avg_20d', sa.BigInteger(), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('breakout_triggered', sa.Boolean(), nullable=False),
    sa.Column('volume_spike_triggered', sa.Boolean(), nullable=False),
    sa.Column('bulk_deal_triggered', sa.Boolean(), nullable=False),
    sa.Column('breakout_details', sa.JSON(), nullable=True),
    sa.Column('volume_spike_details', sa.JSON(), nullable=True),
    sa.Column('bulk_deal_details', sa.JSON(), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reasoning_text', sa.Text(), nullable=True),
    sa.Column('reasoning_generated_at', sa.DateTime(), nullable=True),
    sa.Column('backtest_matches', sa.Integer(), nullable=True),
    sa.Column('backtest_success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('backtest_avg_return', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('backtest_worst_case', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('backtest_best_case', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('backtest_cases_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_run_id', 'symbol', name='uq_scan_result')
    )
    op.create_index('idx_scan_results_composite', 'scan_results', [sa.literal_column('composite_score DESC')], unique=False)
    op.create_index(op.f('ix_scan_results_composite_score'), 'scan_results', ['composite_score'], unique=False)
    op.create_index(op.f('ix_scan_results_id'), 'scan_results', ['id'], unique=False)
    op.create_index(op.f('ix_scan_results_scan_run_id'), 'scan_results', ['scan_run_id'], unique=False)
    op.create_index(op.f('ix_scan_results_symbol'), 'scan_results', ['symbol'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('scan_result_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rr_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_signal', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('score_backtest', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('score_composite', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('outcome_measured', sa.Boolean(), nullable=False),
    sa.Column('outcome_measure_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_exit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('outcome_return_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('outcome_result', sa.String(length=10), nullable=True),
    sa.Column('outcome_measured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_index('idx_decisions_decided_at', 'decisions', [sa.literal_column('decided_at DESC')], unique=False)
    op.create_index(op.f('ix_decisions_action'), 'decisions', ['action'], unique=False)
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_outcome_result'), 'decisions', ['outcome_result'], unique=False)
    op.create_index(op.f('ix_decisions_symbol'), 'decisions', ['symbol'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index('idx_alerts_created_at', 'alerts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index('idx_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_decisions_symbol'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_outcome_result'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_action'), table_name='decisions')
    op.drop_index('idx_decisions_decided_at', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_scan_results_symbol'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_scan_run_id'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_id'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_composite_score'), table_name='scan_results')
    op.drop_index('idx_scan_results_composite', table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_sector'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_scan_runs_status'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_started_at'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_id'), table_name='scan_runs')
    op.drop_index('idx_scan_runs_started_at', table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_market_data_cache_id'), table_name='market_data_cache')
    op.drop_index(op.f('ix_market_data_cache_expires_at'), table_name='market_data_cache')
    op.drop_index('idx_mdc_symbol_type', table_name='market_data_cache')
    op.drop_table('market_data_cache')
    op.drop_index(op.f('ix_bulk_deals_symbol'), table_name='bulk_deals')
    op.drop_index(op.f('ix_bulk_deals_id'), table_name='bulk_deals')
    op.drop_index('idx_bulk_deals_date', table_name='bulk_deals')
    op.drop_table('bulk_deals')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
